export const CORE_EVENTS = [
  "torrent.added",
  "torrent.metadata.received",
  "torrent.progress.updated",
  "torrent.status.changed",
  "torrent.completed",
  "torrent.removed",
  "torrent.labels.updated",
  "torrent.files.updated",
  "torrent.details.updated",
  "torrent.data.moved",
  "torrent.announce.requested",
  "torrent.queue.updated",
  "torrent.error",
  "assistant.health.computed",
  "assistant.schedule.suggestion",
  "network.port.checked",
  "assistant.profile.suggested",
  "assistant.profile.applied",
  "automation.settings.changed",
  "automation.watch.added",
  "automation.watch.scan.completed",
  "diagnostics.speed.checked",
  "diagnostics.torrent_speed.checked",
  "speedDoctor.status.updated",
  "speedDoctor.anomaly.detected",
  "speedDoctor.diagnosis.ready",
  "speedDoctor.report.ready",
  "settings.changed"
] as const;

export const UI_COMMANDS = [
  "torrent.add",
  "torrent.addUrl",
  "torrent.pause",
  "torrent.resume",
  "torrent.forceStart",
  "torrent.remove",
  "torrent.recheck",
  "torrent.rename",
  "torrent.moveData",
  "torrent.reannounce",
  "torrent.exportFile",
  "torrent.setPriority",
  "torrent.setFilePriority",
  "torrent.setFilePriorities",
  "torrent.commitPreparedAdd",
  "torrent.updateQueuePosition",
  "torrent.updateLabels",
  "torrent.updateProfile",
  "automation.update",
  "automation.scanWatchFolders",
  "settings.update",
  "remoteAccess.update"
] as const;

export type CoreEvent = (typeof CORE_EVENTS)[number];
export type UiCommand = (typeof UI_COMMANDS)[number];
